export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';

export const INIT_LANGUAGE = 'INIT_LANGUAGE';
export const INIT_CALENDAR = 'INIT_CALENDAR';
export const INIT_NEWS = 'INIT_NEWS';

export const SETUP_NEWS_FEED = 'SETUP_NEWS_FEED';
export const SETUP_CALENDAR = 'SETUP_CALENDAR';
export const LANGUAGE_CHANGED = 'LANGUAGE_CHANGED';
export const LANGUAGE_CHANGED_START = 'LANGUAGE_CHANGED_START';
export const LANGUAGE_CHANGED_SHOW_HIDE_SPINNER = 'LANGUAGE_CHANGED_SHOW_HIDE_SPINNER';

export const DATA_REQUEST = 'DATA_REQUEST';
export const DATA_RECEIVED = 'DATA_RECEIVED';


export const EMAIL_RECIPIENT_CHANGE = 'EMAIL_RECIPIENT_CHANGE';

export const EMAIL_PROCESS_START = 'EMAIL_PROCESS_START';
export const EMAIL_IN_PROGRESS = 'EMAIL_IN_PROGRESS';
export const EMAIL_SUCCESS = 'EMAIL_SUCCESS';
export const EMAIL_ERROR = 'EMAIL_ERROR';

export const MODAL_OPEN_CLOSE = 'MODAL_OPEN_CLOSE';


