export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE'
export const AUTH_USER = 'AUTH_USER'
export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT'
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'

export const CONTENT_INITIATE = 'CONTENT_INITIATE'
export const SETUP_NEWSFEED = 'SETUP_NEWSFEED'
export const LANGUAGE_CHANGED = 'LANGUAGE_CHANGED'
export const LANGUAGE_CHANGED_START = 'LANGUAGE_CHANGED_START'
export const LANGUAGE_CHANGED_SHOW_HIDE_SPINNER = 'LANGUAGE_CHANGED_SHOW_HIDE_SPINNER'

export const DATA_REQUEST = 'DATA_REQUEST'
export const DATA_RECEIVED = 'DATA_RECEIVED'


